export const mySkills = [
    {
        title:"HTML",
        logo:"images/html.png",
    },
    {
        title:"CSS",
        logo:"images/css.png",
    },
    {
        title:"JS",
        logo:"images/js.png",
    },
    {
        title:"REACT",
        logo:"images/react.png",
    },
    {
        title:"BOOTSTRAP",
        logo:"images/bootstrap5.png",
    },
    {
        title:"MUI",
        logo:"images/materialui.png",
    },
    {
        title:"SASS",
        logo:"images/sass.png",
    },
    {
        title:"GIT",
        logo:"images/git.png",
    },
    {
        title:"GITHUB",
        logo:"images/github.png",
    },
    {
        title:"JIRA",
        logo:"images/jira.png",
    },
]